project:
  type: website
  output-dir: docs


website:
  title: "Zoë J. Kitchel, PhD"
  favicon: "images/favicon.ico"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - href: research.qmd
        text: Research
      - href: publications.qmd
        text: Publications
      - href: media.qmd
        text: Media
      - href: teaching.qmd
        text: Teaching
      - href: contact.qmd
        text: Contact
      - href: files/cv.pdf
        text: CV
      - href: https://bsky.app/profile/zoejean88.bsky.social
        icon: twitter
      - href: https://github.com/zoekitchel
        icon: github

format:
  html:
    theme: litera
    toc: false
    title-block-style: none
    page-layout: full
    css: styles.css
    include-in-header:
      text: |
        <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@700&family=Inter:wght@300;400;600&display=swap" rel="stylesheet">


editor: visual

