project:
  type: website
  output-dir: docs


website:
  title: "Zoë J. Kitchel, PhD"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: research.qmd
        text: Research
      - href: publications.qmd
        text: Publications
      - href: media.qmd
        text: Media
      - href: teaching.qmd
        text: Teaching
      - href: contact.qmd
        text: Contact
      - href: files/cv.pdf
        text: CV
      - href: https://bsky.app/profile/zoejean88.bsky.social
        icon: bluesky
        target: _blank # opens link in a new browser tab
      - href: https://github.com/zoekitchel
        icon: github
        target: _blank # opens link in a new browser tab

format:
  html:
    theme: litera
    css: styles.css
    toc: true

editor: visual

